from __future__ import annotations

from pathlib import Path

from .models import PrimitiveBox


def primitive_volume(box: PrimitiveBox) -> float:
    return float(box.size[0] * box.size[1] * box.size[2])


def primitive_bounds(box: PrimitiveBox) -> tuple[list[float], list[float]]:
    half = [value / 2.0 for value in box.size]
    lower = [center - extent for center, extent in zip(box.center, half)]
    upper = [center + extent for center, extent in zip(box.center, half)]
    return lower, upper


def combine_bounds(boxes: list[PrimitiveBox]) -> tuple[list[float], list[float]]:
    if not boxes:
        return [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]
    lowers, uppers = zip(*(primitive_bounds(box) for box in boxes))
    lower = [min(items[idx] for items in lowers) for idx in range(3)]
    upper = [max(items[idx] for items in uppers) for idx in range(3)]
    return lower, upper


def center_from_bounds(lower: list[float], upper: list[float]) -> list[float]:
    return [(low + high) / 2.0 for low, high in zip(lower, upper)]


def size_from_bounds(lower: list[float], upper: list[float]) -> list[float]:
    return [high - low for low, high in zip(lower, upper)]


def shifted_boxes(boxes: list[PrimitiveBox], translation: list[float]) -> list[PrimitiveBox]:
    shifted: list[PrimitiveBox] = []
    for box in boxes:
        shifted.append(
            PrimitiveBox(
                name=box.name,
                center=[coord - shift for coord, shift in zip(box.center, translation)],
                size=list(box.size),
                observed_ratio=box.observed_ratio,
                generated=box.generated,
                metadata=dict(box.metadata),
            )
        )
    return shifted


def write_obj(path: str | Path, boxes: list[PrimitiveBox]) -> None:
    output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = ["# Generated by rgbd_urdf_mvp"]
    vertex_offset = 1
    for box in boxes:
        half = [value / 2.0 for value in box.size]
        cx, cy, cz = box.center
        vertices = [
            (cx - half[0], cy - half[1], cz - half[2]),
            (cx + half[0], cy - half[1], cz - half[2]),
            (cx + half[0], cy + half[1], cz - half[2]),
            (cx - half[0], cy + half[1], cz - half[2]),
            (cx - half[0], cy - half[1], cz + half[2]),
            (cx + half[0], cy - half[1], cz + half[2]),
            (cx + half[0], cy + half[1], cz + half[2]),
            (cx - half[0], cy + half[1], cz + half[2]),
        ]
        faces = [
            (0, 1, 2),
            (0, 2, 3),
            (4, 5, 6),
            (4, 6, 7),
            (0, 1, 5),
            (0, 5, 4),
            (1, 2, 6),
            (1, 6, 5),
            (2, 3, 7),
            (2, 7, 6),
            (3, 0, 4),
            (3, 4, 7),
        ]
        lines.append(f"o {box.name}")
        for x_coord, y_coord, z_coord in vertices:
            lines.append(f"v {x_coord:.6f} {y_coord:.6f} {z_coord:.6f}")
        for face in faces:
            a_idx, b_idx, c_idx = face
            lines.append(
                f"f {vertex_offset + a_idx} {vertex_offset + b_idx} {vertex_offset + c_idx}"
            )
        vertex_offset += len(vertices)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
